---
#
# - Run this workflow to pull changes from the ML template repository.
# 
#   - Clone this repository. Check out a branch
#   - Copy files from the template onto this clone
#   - Push the branch to this repository
#   - Create a pull request in this repository
#
name: Sync changes from template

on:
  # Run at 0600 UTC each Saturday
  schedule:
    - cron: "06 0 * * 6"

  # Or run when this file changes
  push:
    paths:
      - .github/workflows/sync-from-template.yml

  # Or run when manually triggered
  workflow_dispatch:

env:
  BASE_BRANCH: master
  HEAD_BRANCH: sync-from-template
  GIT_AUTHOR_NAME: ${{ github.repository_owner }}
  GIT_AUTHOR_EMAIL: ${{ github.repository_owner }}@users.noreply.github.com
  REPO_TEMPLATE: building-estimates/ml-model-template
  THIS_REPO: ${{ github.repository }}

jobs:
  sync-from-template:
    # Do not run on the template repository itself
    if: github.repository != 'building-estimates/ml-model-template'
    name: Sync changes from building-estimates/ml-model-template
    runs-on: ubuntu-latest

    steps:
      # Clone the template repository
      - name: Check out template repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_TEMPLATE }}
          token: ${{ github.token }}
          path: ${{ env.REPO_TEMPLATE }}

      # Clone the inference repository. Check out a branch
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          path: ${{ github.repository }}
      - name: Create branch in ${{ env.THIS_REPO }}
        run: |
          git -C "${THIS_REPO}" fetch origin "${HEAD_BRANCH}" || true
          git -C "${THIS_REPO}" branch -a
          git -C "${THIS_REPO}" checkout -B "${HEAD_BRANCH}" \
            "remotes/origin/${HEAD_BRANCH}" || \
          git -C "${THIS_REPO}" checkout -b "${HEAD_BRANCH}"
      
      # Copy files from the template onto the inference repository clone
      - name: Copy template contents
        run: |
          _files="$(find ${REPO_TEMPLATE} \
            ! -path "*/.git/*" \
            ! -path "*/.github/workflows/*" \
            ! -path "*/demo/*" \
            ! -path "*/ml_model/*" \
            ! -name "demo.py" \
            ! -name "setup.py" \
            ! -name ".gitignore" \
            ! -name ".dockerignore" \
            ! -name "README.md" \
            -type f \
            -print)"
          for _file in ${_files}; do
            _src="${_file}"
            _dst="${THIS_REPO}/${_file#${REPO_TEMPLATE}/}"
            # TODO: Find a more robust / elegant way to get this :point_down:
            _dst="${_dst%/*}/"
            mkdir -p "${_dst}"
            echo "INFO: Copy '${_src}' to '${_dst}'."
            cp "${_src}" "${_dst}"
          done

      # Commit changes, if there are any
      - name: Commit changes, if any
        run: |
          git -C ${THIS_REPO} config user.name "${GIT_AUTHOR_NAME}"
          git -C ${THIS_REPO} config \
            user.email "${GIT_AUTHOR_EMAIL}"
          git -C ${THIS_REPO} add .
          git -C ${THIS_REPO} commit \
            -m "Sync from template@${{ github.sha }}"
      # Push the branch to the inference repository
      - name: Push topic branch
        run: git -C ${THIS_REPO} push -u origin "${HEAD_BRANCH}"

      # Create a pull request in the target repository
      - name: Create PR for the inference repository
        run: |
          cd ${THIS_REPO} && \
          gh pr create --base ${BASE_BRANCH} \
           --title 'Merge Sync ML template branch into master' \
           --body 'PR for ML template changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}